name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./carpool-app 
        run: npm install

      - name: Run ESLint
        working-directory: ./carpool-app 
        run: npx eslint .