name: CI/CD

on:
  pull_request:
  push:

jobs:
  # Commented out the linter job
  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       working-directory: ./carpool-app 
  #       run: npm install

  #     - name: Run ESLint
  #       working-directory: ./carpool-app 
  #       run: npx eslint .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./carpool-app
        run: npm install

      - name: Run tests
        working-directory: ./carpool-app
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    needs: 
      - test

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"
