name: CI/CD

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./carpool-app 
        run: npm install

      - name: Run ESLint
        working-directory: ./carpool-app 
        run: npx eslint .

  deploy:
    runs-on: ubuntu-latest
    
    needs: 
      - lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"